SELECT F.CAR_ID, F.CAR_TYPE, S.FEE
FROM
    CAR_RENTAL_COMPANY_CAR F,
    (
        SELECT 
            B.CAR_ID,
            ROUND(B.DAILY_FEE * 30 * (100 - C.DISCOUNT_RATE) * 0.01 ) AS FEE
        FROM CAR_RENTAL_COMPANY_CAR B, CAR_RENTAL_COMPANY_DISCOUNT_PLAN C
        WHERE   B.CAR_TYPE = C.CAR_TYPE
            AND B.CAR_TYPE IN ('세단','SUV')
            AND C.DURATION_TYPE = '30일 이상'
    ) S
WHERE F.CAR_ID NOT IN (
                SELECT CAR_ID
                FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                WHERE '2022-11-01' BETWEEN START_DATE AND END_DATE
                OR '2022-11-01' BETWEEN START_DATE AND END_DATE
                )
        AND F.CAR_ID = S.CAR_ID
        AND S.FEE BETWEEN 500000 AND 1999999
ORDER BY S.FEE DESC, F.CAR_TYPE ASC, F.CAR_ID DESC



# SELECT *
# FROM CAR_RENTAL_COMPANY_CAR F, CAR_RENTAL_COMPANY_RENTAL_HISTORY C
# WHERE F.CAR_ID NOT IN (
#                 SELECT CAR_ID
#                 FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
#                 WHERE '2022-11-01' BETWEEN START_DATE AND END_DATE
#                 OR '2022-11-01' BETWEEN START_DATE AND END_DATE
#                 )
#                 AND F.CAR_ID = C.CAR_ID