#SELECT * FROM CART_PRODUCTS WHERE CART_ID IN (286,448,578,977,1048)
SELECT A.CART_ID
FROM
(SELECT CART_ID FROM CART_PRODUCTS WHERE NAME = "Milk" GROUP BY CART_ID) A
JOIN
(SELECT CART_ID FROM CART_PRODUCTS WHERE NAME = "Yogurt" GROUP BY CART_ID) B
ON A.CART_ID = B.CART_ID