-- 코드를 입력하세요
SELECT a.FLAVOR -- , a.TOTAL_ORDER+b.val as v
FROM FIRST_HALF a,
(SELECT FLAVOR, SUM(TOTAL_ORDER) as val
FROM JULY 
GROUP BY FLAVOR) b
WHERE a.FLAVOR = b.FLAVOR
ORDER BY (a.TOTAL_ORDER+b.val) DESC
LIMIT 3
