-- 코드를 작성해주세요
SELECT  C.ID, D.FISH_NAME, D.LENGTH
FROM    FISH_INFO C, (
SELECT  B.FISH_TYPE, B.FISH_NAME, MAX(LENGTH) AS LENGTH
FROM    FISH_INFO A, FISH_NAME_INFO B
WHERE   A.FISH_TYPE = B.FISH_TYPE
GROUP BY B.FISH_TYPE, B.FISH_NAME) D
WHERE   C.FISH_TYPE = D.FISH_TYPE
AND     C.LENGTH = D.LENGTH
ORDER BY ID ASC